config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  devise_for :users, class_name: "Users::User"
  as :user do
    get 'users/edit' => 'devise/registrations#edit', :as => 'edit_user_registration'
    put 'users' => 'devise/registrations#update', :as => 'user_registration'
  end

  authenticate :user do
    mount Sidekiq::Web => '/sidekiq'
  end

  root to: 'imports/imports#index'

  resources :imports, module: 'imports', as: :imports_imports do
    resources :transfers, as: :imports_transfers
    resources :migrations, as: :migrations do
      post :start, on: :member
    end
    resources :exports, as: :exports do
      post :start, on: :member
    end
  end
end

app/models/export.rb
class Export < ApplicationRecord
  include StatusAwareConcern
  include LoggableConcern

  belongs_to :import, class_name: 'Imports::Import'
  has_many :table_exports, dependent: :destroy
  has_many :tables, class_name: 'Imports::Table', through: :table_exports

  def update_status!
    table_exports.reload
    self.status = 'failed' if table_exports.any? { |te| te.failed? }
    save!
  end
end

app/models/imports.rb
module Imports
  def self.table_name_prefix
    'imports_'
  end
end

app/models/imports/import.rb
class Imports::Import < ApplicationRecord
  enum status: {active: 0, disabled: 10}

  has_many :tables, class_name: 'Imports::Table', inverse_of: :import
  has_many :transfers, class_name: 'Imports::Transfer', inverse_of: :import
  has_many :migrations, class_name: 'Imports::Migration', inverse_of: :import
  has_many :exports, inverse_of: :import

  validates :title, presence: true
  validates :status, presence: true, inclusion: { in: Imports::Import.statuses.keys }

  accepts_nested_attributes_for :tables, :reject_if => :all_blank, :allow_destroy => true
end

app/models/imports/migration.rb
class Imports::Migration < ApplicationRecord
  include StatusAwareConcern
  include LoggableConcern

  belongs_to :import, class_name: 'Imports::Import', inverse_of: :migrations

  validates :import, presence: true
  validates :sql, presence: true, length: { minimum: 10 }
end

app/models/imports/table.rb
class Imports::Table < ApplicationRecord
  enum strategy: {incremental: 0, rotate: 10}

  belongs_to :import, class_name: 'Imports::Import'
  has_many :table_transfers, class_name: 'Imports::TableTransfer'

  validates :import, presence: true
  validates :name, presence: true
  validates :strategy, presence: true, inclusion: { in: Imports::Table.strategies.keys }
end

app/models/imports/table_transfer.rb
class Imports::TableTransfer < ApplicationRecord
  include StatusAwareConcern

  belongs_to :transfer, class_name: 'Imports::Transfer'
  belongs_to :table, class_name: 'Imports::Table'

  validates :transfer, presence: true
  validates :table, presence: true

  after_commit :update_transfer_status, on: :update

  private

  def update_transfer_status
    transfer.update_status!
  end
end

app/models/imports/transfer.rb
class Imports::Transfer < ApplicationRecord
  include StatusAwareConcern
  include LoggableConcern

  belongs_to :import, class_name: 'Imports::Import'
  has_many :table_transfers, class_name: 'Imports::TableTransfer', dependent: :destroy
  has_many :tables, class_name: 'Imports::Table', through: :table_transfers

  validates :import, presence: true

  def update_status!
    table_transfers.reload

    self.status = 'failed' if table_transfers.any? { |tt| tt.failed? }
    # self.status = 'finished' if table_transfers.all? { |tt| tt.finished? }

    save!
  end
end

app/controllers/imports/exports_controller.rb
class Imports::ExportsController < ApplicationController
  before_action :set_import
  before_action :set_export, only: [:show, :edit, :update, :destroy]

  def index
    @exports = @import.exports
  end

  def new
    @export = @import.exports.build
  end

  def show
  end

  def edit
  end

  def start
    DoExportJob.perform_later(@export)
    redirect_to [@import, :exports], notice: "Export started!"
  end

  def create
    @export = @import.exports.build({})
    @export.status = :pending

    @import.tables.each do |table|
      @export.table_exports.build(status: 'pending', table: table)
    end

    respond_to do |format|
      if @export.save
        format.html { redirect_to [@import, :exports], notice: "Export was successfully created." }
        format.json { render :show, status: :created, location: @export }
      else
        format.html { render :new }
        format.json { render json: @export.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
  end

  def destroy
    @export.destroy
    respond_to do |format|
      format.html { redirect_to [@import, :exports], notice: 'Export was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

    # Use callbacks to share common setup or constraints between actions.
    def set_import
      @import = Imports::Import.find(params[:imports_import_id])
    end

    def set_export
      @export = @import.exports.find(params[:id])
    end
end

app/controllers/imports/imports_controller.rb
class Imports::ImportsController < ApplicationController
  before_action :set_imports_import, only: [:show, :edit, :update, :destroy]

  # GET /imports/imports
  # GET /imports/imports.json
  def index
    @imports_imports = Imports::Import.all
  end

  # GET /imports/imports/1
  # GET /imports/imports/1.json
  def show
  end

  # GET /imports/imports/new
  def new
    @imports_import = Imports::Import.new(postgres: {}, s3: {}, redshift: {})
  end

  # GET /imports/imports/1/edit
  def edit
  end

  # POST /imports/imports
  # POST /imports/imports.json
  def create
    @imports_import = Imports::Import.new(imports_import_params)

    respond_to do |format|
      if @imports_import.save
        format.html { redirect_to imports_imports_url, notice: "#{@imports_import.title} was successfully created." }
        format.json { render :show, status: :created, location: @imports_import }
      else
        format.html { render :new }
        format.json { render json: @imports_import.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /imports/imports/1
  # PATCH/PUT /imports/imports/1.json
  def update
    respond_to do |format|
      if @imports_import.update(imports_import_params)
        format.html { redirect_to imports_imports_url, notice: "#{@imports_import.title} was successfully updated." }
        format.json { render :show, status: :ok, location: @imports_import }
      else
        format.html { render :edit }
        format.json { render json: @imports_import.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /imports/imports/1
  # DELETE /imports/imports/1.json
  def destroy
    @imports_import.destroy
    respond_to do |format|
      format.html { redirect_to imports_imports_url, notice: 'Import was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_imports_import
      @imports_import = Imports::Import.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def imports_import_params
      attrs = params.require(:imports_import).permit(
                :title, :redshift, :postgres, :postgres_to_export_to, :s3, :status,
                :private_ssh_key_to_postgres_server,
                tables_attributes: [:id, :name, :strategy, :init_sql_script, :select_sql, :_destroy])

      attrs[:redshift] = JSON.parse(attrs[:redshift] || '{}')
      attrs[:postgres] = JSON.parse(attrs[:postgres] || '{}')
      attrs[:postgres_to_export_to] = JSON.parse(attrs[:postgres_to_export_to] || '{}')
      attrs[:s3] = JSON.parse(attrs[:s3] || '{}')

      attrs
    end
end

app/controllers/imports/migrations_controller.rb
class Imports::MigrationsController < ApplicationController
  before_action :set_import
  before_action :set_migration, only: [:show, :edit, :update, :destroy, :start]

  def index
    @migrations = @import.migrations
  end

  def new
    @migration = @import.migrations.build
  end

  def show
  end

  def edit
  end

  def start
    DoMigrationJob.perform_later(@migration)
    redirect_to [@import, :migrations], notice: "Migration started!"
  end

  def create
    @migration = @import.migrations.build(migration_params)
    @migration.status = :pending

    respond_to do |format|
      if @migration.save
        format.html { redirect_to [@import, :migrations], notice: "Migration was successfully created." }
        format.json { render :show, status: :created, location: @migration }
      else
        format.html { render :new }
        format.json { render json: @migration.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @migration.update(migration_params)
        format.html { redirect_to [@import, :migrations], notice: "Migration was successfully updated." }
        format.json { render :show, status: :ok, location: @migration }
      else
        format.html { render :edit }
        format.json { render json: @migration.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @migration.destroy
    respond_to do |format|
      format.html { redirect_to [@import, :migrations], notice: 'Migration was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

    # Use callbacks to share common setup or constraints between actions.
    def set_import
      @import = Imports::Import.find(params[:imports_import_id])
    end

    def set_migration
      @migration = @import.migrations.find(params[:id])
    end

    def migration_params
      params.require(:imports_migration).permit(:sql)
    end
end

app/controllers/imports/transfers_controller.rb
class Imports::TransfersController < ApplicationController
  before_action :set_imports_import

  def create
    ImportStarterJob.perform_later @imports_import
    redirect_to imports_import_url(@imports_import), notice: "You've started a new transfer!"
  end

  def update
    @transfer = @imports_import.transfers.find(params[:id])

    TransferStarterJob.perform_later @transfer
    redirect_to imports_import_url(@imports_import), notice: "You've restarted the transfer!"
  end

  def show
    @transfer = @imports_import.transfers.find(params[:id])
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_imports_import
      @imports_import = Imports::Import.find(params[:imports_import_id])
    end
end

app/helpers/imports/imports_helper.rb
module Imports::ImportsHelper
end

app/views/imports/exports/_export.html.erb
<tr class="<%= bootstrap_row_class_for_status export.status %>">
  <td><%= export.id %></td>
  <td><%= export.status %></td>

  <td>
    <% unless export.started? %>
      <%= link_to start_imports_import_export_path(export.import, export), method: :post, class: 'btn btn-xs btn-default btn-success' do %>
        <span class="glyphicon glyphicon-refresh" aria-hidden="true"></span>
      <% end %>
    <% end %>
    <%= link_to imports_import_export_path(export.import, export), class: 'btn btn-xs btn-default' do %>
      <span class="glyphicon glyphicon-eye-open" aria-hidden="true"></span>
    <% end %>
    <%= link_to edit_imports_import_export_path(export.import, export), class: 'btn btn-xs btn-default' do %>
      <span class="glyphicon glyphicon-pencil" aria-hidden="true"></span>
    <% end %>
    <%= link_to imports_import_export_path(export.import, export), method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-xs btn-default' do %>
      <span class="glyphicon glyphicon-trash" aria-hidden="true"></span>
    <% end %>
  </td>
</tr>

app/views/imports/exports/_form.html.erb
<% url = export.new_record? ? imports_import_exports_path(export.import) : imports_import_export_path(export.import, export) %>

<%= simple_form_for(export, url: url) do |f| %>
  <%= f.error_notification %>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/imports/exports/edit.html.erb
<%= render partial: 'imports/imports/header', locals: {import: @import} %>

<h2>
  Editing Export

  <%= link_to imports_import_export_path(@import, @export), class: 'pull-right btn btn-default' do %>
    <span class="glyphicon glyphicon-eye-open" aria-hidden="true"></span>
  <% end %>
  <%= link_to [@import, :exports], class: 'pull-right btn btn-default' do %>
    <span class="glyphicon glyphicon-arrow-left" aria-hidden="true"></span>
  <% end %>
</h2>
<hr/>

<%= render 'form', export: @export %>

app/views/imports/exports/index.html.erb
<%= render partial: 'imports/imports/header', locals: {import: @import} %>

<div class='row'>
  <div class='col-md-8'>
    <h3>Exports</h3>
  </div>
  <div class="col-md-4">
    <%= link_to [:new, @import, :export], class: 'pull-right btn btn-default btn-success' do %>
      <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>
      &nbsp;New Export
    <% end %>
  </div>
</div>

<table class='table'>
  <thead>
    <tr>
      <th>#</th>
      <th>Status</th>
      <th>Actions</th>
    </tr>
  </thead>

  <tbody>
    <%= render @exports, as: :export %>
  </tbody>
</table>

<br>

app/views/imports/exports/new.html.erb
<%= render partial: 'imports/imports/header', locals: {import: @import} %>

<h2>
  New Export

  <%= link_to [@import, :exports], class: 'pull-right btn btn-default' do %>
    <span class="glyphicon glyphicon-arrow-left" aria-hidden="true"></span>
  <% end %>
</h2>
<hr/>

<%= render 'form', export: @export %>

app/views/imports/exports/show.html.erb
<%= render partial: 'imports/imports/header', locals: {import: @import} %>

<h2>
  Export

  <%= link_to [@import, :exports], class: 'pull-right btn btn-default' do %>
    <span class="glyphicon glyphicon-arrow-left" aria-hidden="true"></span>
  <% end %>
</h2>
<hr/>

<table class='table'>
  <tr>
    <td>Started at</td>
    <td><%= @export.created_at %></td>
  </tr>
  <tr>
    <td>Finished at</td>
    <td><%= @export.finished_at %></td>
  </tr>
  <tr>
    <td>Status</td>
    <td><%= @export.status %></td>
  </tr>
</table>

<h3>Table exports</h3>
<table class='table'>
  <thead>
    <tr>
      <th>#</th>
      <th>Table</th>
      <th>Started at</th>
      <th>Finished at</th>
      <th>Status</th>
    </tr>
  </thead>

  <tbody>
    <% @export.table_exports.order(id: :asc).each do |table_export| %>
      <tr class="<%= bootstrap_row_class_for_status table_export.status %>">
        <td><%= table_export.id %></td>
        <td><%= table_export.table.name %></td>
        <td><%= table_export.created_at %></td>
        <td><%= table_export.finished_at %></td>
        <td><%= table_export.status %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<p>
  <pre><%= raw @export.log %></pre>
</p>