config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  devise_for :users, class_name: "Users::User"
  as :user do
    get 'users/edit' => 'devise/registrations#edit', :as => 'edit_user_registration'
    put 'users' => 'devise/registrations#update', :as => 'user_registration'
  end

  authenticate :user do
    mount Sidekiq::Web => '/sidekiq'
  end

  root to: 'imports/imports#index'

  resources :imports, module: 'imports', as: :imports_imports do
    resources :transfers, as: :imports_transfers
    resources :migrations, as: :migrations do
      post :start, on: :member
    end
    resources :exports, as: :exports do
      post :start, on: :member
    end
  end
end

app/models/imports.rb
module Imports
  def self.table_name_prefix
    'imports_'
  end
end

app/models/imports/import.rb
class Imports::Import < ApplicationRecord
  enum status: {active: 0, disabled: 10}

  has_many :tables, class_name: 'Imports::Table', inverse_of: :import
  has_many :transfers, class_name: 'Imports::Transfer', inverse_of: :import
  has_many :migrations, class_name: 'Imports::Migration', inverse_of: :import
  has_many :exports, inverse_of: :import

  validates :title, presence: true
  validates :status, presence: true, inclusion: { in: Imports::Import.statuses.keys }

  accepts_nested_attributes_for :tables, :reject_if => :all_blank, :allow_destroy => true
end

app/models/imports/migration.rb
class Imports::Migration < ApplicationRecord
  include StatusAwareConcern
  include LoggableConcern

  belongs_to :import, class_name: 'Imports::Import', inverse_of: :migrations

  validates :import, presence: true
  validates :sql, presence: true, length: { minimum: 10 }
end

app/models/imports/table.rb
class Imports::Table < ApplicationRecord
  enum strategy: {incremental: 0, rotate: 10}

  belongs_to :import, class_name: 'Imports::Import'
  has_many :table_transfers, class_name: 'Imports::TableTransfer'

  validates :import, presence: true
  validates :name, presence: true
  validates :strategy, presence: true, inclusion: { in: Imports::Table.strategies.keys }
end

app/models/imports/table_transfer.rb
class Imports::TableTransfer < ApplicationRecord
  include StatusAwareConcern

  belongs_to :transfer, class_name: 'Imports::Transfer'
  belongs_to :table, class_name: 'Imports::Table'

  validates :transfer, presence: true
  validates :table, presence: true

  after_commit :update_transfer_status, on: :update

  private

  def update_transfer_status
    transfer.update_status!
  end
end

app/models/imports/transfer.rb
class Imports::Transfer < ApplicationRecord
  include StatusAwareConcern
  include LoggableConcern

  belongs_to :import, class_name: 'Imports::Import'
  has_many :table_transfers, class_name: 'Imports::TableTransfer', dependent: :destroy
  has_many :tables, class_name: 'Imports::Table', through: :table_transfers

  validates :import, presence: true

  def update_status!
    table_transfers.reload

    self.status = 'failed' if table_transfers.any? { |tt| tt.failed? }
    # self.status = 'finished' if table_transfers.all? { |tt| tt.finished? }

    save!
  end
end

app/controllers/imports/exports_controller.rb
class Imports::ExportsController < ApplicationController
  before_action :set_import
  before_action :set_export, only: [:show, :edit, :update, :destroy]

  def index
    @exports = @import.exports
  end

  def new
    @export = @import.exports.build
  end

  def show
  end

  def edit
  end

  def start
    DoExportJob.perform_later(@export)
    redirect_to [@import, :exports], notice: "Export started!"
  end

  def create
    @export = @import.exports.build({})
    @export.status = :pending

    @import.tables.each do |table|
      @export.table_exports.build(status: 'pending', table: table)
    end

    respond_to do |format|
      if @export.save
        format.html { redirect_to [@import, :exports], notice: "Export was successfully created." }
        format.json { render :show, status: :created, location: @export }
      else
        format.html { render :new }
        format.json { render json: @export.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
  end

  def destroy
    @export.destroy
    respond_to do |format|
      format.html { redirect_to [@import, :exports], notice: 'Export was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

    # Use callbacks to share common setup or constraints between actions.
    def set_import
      @import = Imports::Import.find(params[:imports_import_id])
    end

    def set_export
      @export = @import.exports.find(params[:id])
    end
end

app/controllers/imports/imports_controller.rb
class Imports::ImportsController < ApplicationController
  before_action :set_imports_import, only: [:show, :edit, :update, :destroy]

  # GET /imports/imports
  # GET /imports/imports.json
  def index
    @imports_imports = Imports::Import.all
  end

  # GET /imports/imports/1
  # GET /imports/imports/1.json
  def show
  end

  # GET /imports/imports/new
  def new
    @imports_import = Imports::Import.new(postgres: {}, s3: {}, redshift: {})
  end

  # GET /imports/imports/1/edit
  def edit
  end

  # POST /imports/imports
  # POST /imports/imports.json
  def create
    @imports_import = Imports::Import.new(imports_import_params)

    respond_to do |format|
      if @imports_import.save
        format.html { redirect_to imports_imports_url, notice: "#{@imports_import.title} was successfully created." }
        format.json { render :show, status: :created, location: @imports_import }
      else
        format.html { render :new }
        format.json { render json: @imports_import.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /imports/imports/1
  # PATCH/PUT /imports/imports/1.json
  def update
    respond_to do |format|
      if @imports_import.update(imports_import_params)
        format.html { redirect_to imports_imports_url, notice: "#{@imports_import.title} was successfully updated." }
        format.json { render :show, status: :ok, location: @imports_import }
      else
        format.html { render :edit }
        format.json { render json: @imports_import.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /imports/imports/1
  # DELETE /imports/imports/1.json
  def destroy
    @imports_import.destroy
    respond_to do |format|
      format.html { redirect_to imports_imports_url, notice: 'Import was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_imports_import
      @imports_import = Imports::Import.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def imports_import_params
      attrs = params.require(:imports_import).permit(
                :title, :redshift, :postgres, :postgres_to_export_to, :s3, :status,
                :private_ssh_key_to_postgres_server,
                tables_attributes: [:id, :name, :strategy, :init_sql_script, :select_sql, :_destroy])

      attrs[:redshift] = JSON.parse(attrs[:redshift] || '{}')
      attrs[:postgres] = JSON.parse(attrs[:postgres] || '{}')
      attrs[:postgres_to_export_to] = JSON.parse(attrs[:postgres_to_export_to] || '{}')
      attrs[:s3] = JSON.parse(attrs[:s3] || '{}')

      attrs
    end
end

app/controllers/imports/migrations_controller.rb
class Imports::MigrationsController < ApplicationController
  before_action :set_import
  before_action :set_migration, only: [:show, :edit, :update, :destroy, :start]

  def index
    @migrations = @import.migrations
  end

  def new
    @migration = @import.migrations.build
  end

  def show
  end

  def edit
  end

  def start
    DoMigrationJob.perform_later(@migration)
    redirect_to [@import, :migrations], notice: "Migration started!"
  end

  def create
    @migration = @import.migrations.build(migration_params)
    @migration.status = :pending

    respond_to do |format|
      if @migration.save
        format.html { redirect_to [@import, :migrations], notice: "Migration was successfully created." }
        format.json { render :show, status: :created, location: @migration }
      else
        format.html { render :new }
        format.json { render json: @migration.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @migration.update(migration_params)
        format.html { redirect_to [@import, :migrations], notice: "Migration was successfully updated." }
        format.json { render :show, status: :ok, location: @migration }
      else
        format.html { render :edit }
        format.json { render json: @migration.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @migration.destroy
    respond_to do |format|
      format.html { redirect_to [@import, :migrations], notice: 'Migration was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

    # Use callbacks to share common setup or constraints between actions.
    def set_import
      @import = Imports::Import.find(params[:imports_import_id])
    end

    def set_migration
      @migration = @import.migrations.find(params[:id])
    end

    def migration_params
      params.require(:imports_migration).permit(:sql)
    end
end

app/controllers/imports/transfers_controller.rb
class Imports::TransfersController < ApplicationController
  before_action :set_imports_import

  def create
    ImportStarterJob.perform_later @imports_import
    redirect_to imports_import_url(@imports_import), notice: "You've started a new transfer!"
  end

  def update
    @transfer = @imports_import.transfers.find(params[:id])

    TransferStarterJob.perform_later @transfer
    redirect_to imports_import_url(@imports_import), notice: "You've restarted the transfer!"
  end

  def show
    @transfer = @imports_import.transfers.find(params[:id])
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_imports_import
      @imports_import = Imports::Import.find(params[:imports_import_id])
    end
end

app/helpers/imports/imports_helper.rb
module Imports::ImportsHelper
end

app/views/imports/imports/_form.html.erb
<%= simple_form_for(@imports_import) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :title %>

    <%= f.input :postgres, as: :text, input_html: {value: JSON.generate(f.object.postgres)}, hint: 'e.g {"host": "127.0.0.1", "user": "postgres", "password":"superpass123", "name":"my_db", "port": 5432}' %>
    <%= f.input :postgres_to_export_to, as: :text, input_html: {value: JSON.generate(f.object.postgres_to_export_to)}, hint: 'e.g {"host": "127.0.0.1", "user": "postgres", "password":"superpass123", "name":"my_db", "port": 5432}' %>

    <%= f.input :s3, as: :text, input_html: {value: JSON.generate(f.object.s3)}, hint: 'e.g {"access_key_id": "123456", "secret_access_key": "ZXCVBN", "bucket": "my-bucket-name", "region": "us-east-1"}' %>
    <%= f.input :redshift, as: :text, input_html: {value: JSON.generate(f.object.redshift)}, hint: 'e.g {}' %>
    <%= f.input :status, collection: Imports::Import.statuses.keys %>

    <h3>Tables</h3>
    <div id='tables'>
      <%= f.simple_fields_for :tables do |table| %>
        <%= render 'table_fields', f: table %>
      <% end %>
      <div class='links'>
        <%= link_to_add_association f, :tables, class: 'btn btn-default' do %>
          <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>
        <% end %>
      </div>
    </div>
    </br>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/imports/imports/_header.html.erb
<h2>
  Import <%= import.title %>

  <%= link_to import, class: 'pull-right btn btn-default' do %>
    <span class="glyphicon glyphicon-arrow-left" aria-hidden="true"></span>
  <% end %>
</h2>
<hr/>

app/views/imports/imports/_import.html.erb
<tr>
  <td><%= import.title %></td>
  <td><%= import.status %></td>
  <td><%= import.tables.count %> tables</td>

  <% if transfer = import.transfers.order(id: :desc).first %>
    <td class='<%= bootstrap_row_class_for_status transfer.status %>'>
        <%= transfer.created_at %> / <%= transfer.status %>
    </td>
  <% else %>
    <td>Never</td>
  <% end %>

  <td>
    <%= link_to import, class: 'btn btn-xs btn-default' do %>
      <span class="glyphicon glyphicon-eye-open" aria-hidden="true"></span>
    <% end %>
    <%= link_to edit_imports_import_path(import), class: 'btn btn-xs btn-default' do %>
      <span class="glyphicon glyphicon-pencil" aria-hidden="true"></span>
    <% end %>
    <%= link_to import, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-xs btn-default' do %>
      <span class="glyphicon glyphicon-trash" aria-hidden="true"></span>
    <% end %>
  </td>
</tr>

app/views/imports/imports/_table_fields.html.erb
<div class='nested-fields well well-sm'>
  <%= f.input :name %>
  <%= f.input :strategy, collection: Imports::Table.strategies.keys %>
  <%= f.input :init_sql_script %>
  <%= f.input :select_sql %>
  <%= link_to_remove_association f, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-trash" aria-hidden="true"></span>
  <% end %>
</div>

app/views/imports/imports/edit.html.erb
<h2>
  Editing Import

  <%= link_to @imports_import, class: 'pull-right btn btn-default' do %>
    <span class="glyphicon glyphicon-eye-open" aria-hidden="true"></span>
  <% end %>
  <%= link_to imports_imports_path, class: 'pull-right btn btn-default' do %>
    <span class="glyphicon glyphicon-arrow-left" aria-hidden="true"></span>
  <% end %>
</h2>
<hr/>

<%= render 'form', imports_import: @imports_import %>

app/views/imports/imports/index.html.erb
<h2>
  Imports
  <%= link_to new_imports_import_path, class: 'pull-right' do %>
    <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>
  <% end %>
</h2>

<table class='table'>
  <thead>
    <tr>
      <th colspan="3">Meta</th>
      <th>Last transfer</th>
      <th>Actions</th>
    </tr>
  </thead>

  <tbody>
    <%= render @imports_imports, as: :imports_import %>
  </tbody>
</table>

<br>

app/views/imports/imports/new.html.erb
<h2>
  New Import
  <%= link_to imports_imports_path, class: 'pull-right' do %>
    <span class="glyphicon glyphicon-arrow-left" aria-hidden="true"></span>
  <% end %>
</h2>
<hr/>

<%= render 'form', imports_import: @imports_import %>

app/views/imports/imports/show.html.erb
<h2>
  Import <%= @imports_import.title %>

  <%= link_to [@imports_import, :migrations], class: 'pull-right btn btn-default' do %>
    <span class="glyphicon glyphicon-king" aria-hidden="true"></span>
    Migrations
  <% end %>
  <%= link_to [@imports_import, :exports], class: 'pull-right btn btn-default' do %>
    <span class="glyphicon glyphicon-king" aria-hidden="true"></span>
    Exports
  <% end %>
  <%= link_to edit_imports_import_path(@imports_import), class: 'pull-right btn btn-default' do %>
    <span class="glyphicon glyphicon-pencil" aria-hidden="true"></span>
  <% end %>
  <%= link_to imports_imports_path, class: 'pull-right btn btn-default' do %>
    <span class="glyphicon glyphicon-arrow-left" aria-hidden="true"></span>
  <% end %>
</h2>
<hr/>

<div class='row'>
  <div class='col-md-8'>
    <h3>Transfers</h3>
  </div>
  <div class="col-md-4">
    <%= button_to imports_import_imports_transfers_path(@imports_import), method: :post, class: 'pull-right btn btn-default btn-success' do %>
      <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>
      &nbsp;Start transfer
    <% end %>
  </div>
</div>

<table class='table'>
  <thead>
    <tr>
      <td>#</td>
      <th>Started at</th>
      <th>Finished at</th>
      <th>Status</th>
      <th>Actions</th>
    </tr>
  </thead>

  <tbody>
    <% @imports_import.transfers.order(id: :desc).each do |transfer| %>
      <tr class="<%= bootstrap_row_class_for_status transfer.status %>">
        <td><%= transfer.id %></td>
        <td><%= transfer.created_at %></td>
        <td><%= transfer.finished_at %></td>
        <td><%= transfer.status %></td>
        <td>
          <%= link_to [@imports_import, transfer], class: 'btn btn-xs btn-default' do %>
            <span class="glyphicon glyphicon-eye-open" aria-hidden="true"></span>
          <% end %>

          <% if transfer.failed? %>
            <%= link_to [@imports_import, transfer], method: :put, class: 'btn btn-xs btn-default btn-success' do %>
              <span class="glyphicon glyphicon-refresh" aria-hidden="true"></span>
            <% end %>
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>